[mypy]
python_version = 3.11

[mypy-asyncache]
ignore_missing_imports = True

[mypy-cachetools]
ignore_missing_imports = True

[mypy-googleapiclient.*]
ignore_missing_imports = True

[mypy-google_auth_oauthlib.*]
ignore_missing_imports = True
